#Application Env
# dev : Development, prod: Production
APP_ENV : dev

APP_LOCALE : fr
APP_CHARSET : utf-8

DATABASE_HOST : 127.0.0.1
DATABASE_PORT : 3306
DATABASE_NAME : oc_blog
DATABASE_USERNAME : username
DATABASE_PASSWORD : password

MAILER_TRANSPORT : smtp
MAILER_HOST : ~
MAILER_USER : ~
MAILER_PASSWORD : ~
