#Application Env
# dev : Development, prod: Production
APP_ENV : prod

APP_LOCALE : fr
APP_CHARSET : utf-8

#Database
DATABASE_HOST : 
DATABASE_PORT : 
DATABASE_NAME : 
DATABASE_USERNAME : 
DATABASE_PASSWORD : 

#Mailer
MAILER_TRANSPORT : smtp
MAILER_HOST : ~
MAILER_USER : ~
MAILER_PASSWORD : ~

#Uploads
ACCEPTED_TYPES: png,jpeg,pdf
MAX_SIZE_IMAGE: 300000
MAX_SIZE_PDF: 500000