#Application Env
# dev : Development, prod: Production
APP_ENV : dev

APP_LOCALE : fr
APP_CHARSET : utf-8

#Database
DATABASE_HOST : 127.0.0.1
DATABASE_PORT : 3308
DATABASE_NAME : blog
DATABASE_USERNAME : root
DATABASE_PASSWORD : ''

#Mailer
MAILER_TRANSPORT : smtp
MAILER_HOST : ~
MAILER_USER : ~
MAILER_PASSWORD : ~

#Uploads
ACCEPTED_TYPES: png,jpeg,pdf
MAX_SIZE_IMAGE: 300000
MAX_SIZE_PDF: 500000

