#Routes
---
#FRONT OFFICE#######################
-
  uri: ^/$
  package: front
  controller: profile
  action: displayProfile
-
  uri: ^/profile[/]?$
  package: front
  controller: profile
  action: displayProfile
-
  uri: ^/contact[/]?$
  package: front
  controller: profile
  action: displayContactForm
-
  uri: ^/contact/send?$
  package: front
  controller: profile
  action: sendContactForm
-
  uri: ^/blog[/]?$
  package: front
  controller: blog
  action: postList
-
  uri: ^/blog/post-([0-9]+)$
  package: front
  controller: blog
  action: displayPost
-
  uri: ^/blog/post-([0-9]+)/send-comment$
  package: front
  controller: blog
  action: sendComment

  #BACKOFFICE #######################

  #POSTS
-
  uri: ^/admin[/]?$
  package: admin
  controller: posts
  action: postList
-
  uri: ^/admin/posts[/]?$
  package: admin
  controller: posts
  action: postList
-
  uri: ^/admin/posts/\?order=[a-zA-Z0-9_]{3,20}$
  package: admin
  controller: posts
  action: postList
-
  uri: ^/admin/posts/\?page=[0-9]{1,100}$
  package: admin
  controller: posts
  action: postList
-
  uri: ^/admin/posts/post-([0-9]+)$
  package: admin
  controller: posts
  action: editPost
-
  uri: ^/admin/posts/new-post$
  package: admin
  controller: posts
  action: newPost
-
  uri: ^/admin/posts/remove=([0-9]+)$
  package: admin
  controller: posts
  action: removePost

  #PROFILE
-
  uri: ^/admin/my-profile$
  package: admin
  controller: profile
  action: editProfile
-
  uri: ^/admin/my-profile/register$
  package: admin
  controller: profile
  action: registerProfile

  #PROFESSIONAL
-
  uri: ^/admin/professional$
  package: admin
  controller: professional
  action: displayProfessional
-
  uri: ^/admin/professional/social$
  package: admin
  controller: professional
  action: displayNetworks
-
  uri: ^/admin/professional/social/add=([0-9]+)$
  package: admin
  controller: professional
  action: addNetwork
-
  uri: ^/admin/professional/social/remove=([0-9]+)$
  package: admin
  controller: professional
  action: removeNetwork

  #COMMENTS
-
  uri: ^/admin/comments[/]?$
  package: admin
  controller: comments
  action: commentsList
-
  uri: ^/admin/comments/comment-([0-9]+)$
  package: admin
  controller: comments
  action: editComment
-
  uri: ^/admin/comments/remove=([0-9]+)$
  package: admin
  controller: comments
  action: removeComment

#AUTHENTICATION#######################
-
  uri: ^/auth/first-time$
  package: authentication
  controller: authentication
  action: displayAdminForm
-
  uri: ^/auth/register$
  package: authentication
  controller: authentication
  action: registerAdmin
-
  uri: ^/auth[/]?$
  package: authentication
  controller: authentication
  action: displaySigninForm
-
  uri: ^/auth/signin[/]?$
  package: authentication
  controller: authentication
  action: signin
-
  uri: ^/admin/change-password$
  package: authentication
  controller: authentication
  action: changePassword
-
  uri: ^/admin/change-password-form$
  package: authentication
  controller: authentication
  action: displayChangePasswordForm





